### ISSUE TITLE
Error: org.objectweb.asm.MethodTooLargeException: Method too large

### ISSUE THREAD

**Issue by AsjadSiddiqui** [ThexXTURBOXx/dex2jar#16]
[summary.txt](https://github.com/ThexXTURBOXx/dex2jar/files/7441339/summary.txt)

Got this error when decompiling APK

**Comment by ThexXTURBOXx** [comment]
Forgot to tell you btw. In December (I think), @pxb1988 introduced decoding and encoding of large arrays which could solve this issue in *some* cases. Maybe, it also works for you now?
