### ISSUE TITLE
Trying to execute d2j-dex2jar.sh after giving executable permission , result in -bash: ./d2j-dex2jar.sh: /bin/sh^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by vramasam** [ThexXTURBOXx/dex2jar#17]
Hello @ThexXTURBOXx 

We try to execute the following command in the mac OS after giving full permission results:
MacBook-Pro:$ ./d2j-dex2jar.sh -f -o /Users/Desktop/classes.jar /Users/Desktop/classes.dex
-bash: ./d2j-dex2jar.sh: /bin/sh^M: bad interpreter: No such file or directory

The above error is coming if we give the executable permission to the file "chmod +x d2j-dex2jar.sh". We like to know the reason for this problem.

**Comment by ThexXTURBOXx** [comment]
Thanks for reporting this issue!
I think, the problem is a CRLF line ending, which is the default on Windows systems.
However, Unix based systems by default only use LF line endings.
I will try to fix the issue as soon as I am done with university today.

**Comment by ThexXTURBOXx** [comment]
Just looked at the relevant sh files, but I can't see why it fails for you.
All the line endings are in the correct format. You could try changing the line endings for you individually.
Or you execute the relevant commands manually.
As already said, I can't really tell why your files don't have the correct line endings,

**Comment by vramasam** [comment]
Okay Thank you @ThexXTURBOXx .
