### ISSUE TITLE
Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by IChooseYou** [ThexXTURBOXx/dex2jar#19]
java -jar d2j-jar2dex.sh classes_patched.jar 
Error: Invalid or corrupt jarfile d2j-jar2dex.sh

JAR file is the same one dex2jar produced. How come?

**Comment by ThexXTURBOXx** [comment]
Not enough information given. Please also provide the jar file you are working with or describe where I can get the jar file from.

**Comment by IChooseYou** [comment]
[](url
[classes.jar.txt](https://github.com/ThexXTURBOXx/dex2jar/files/8765991/classes.jar.txt)
)

**Comment by ThexXTURBOXx** [comment]
I just noticed what is wrong... I should have read more carefully :)
Your command looks like this: `java -jar d2j-jar2dex.sh classes_patched.jar`
This tells java to run the jar file `d2j-jar2dex.sh` with `classes_patched.jar` as an argument.
If you are on Linux/Ubuntu, please try `d2j-jar2dex.sh classes_patched.jar` instead.
If you are on Windows, do `d2j-jar2dex.bat classes_patched.jar`
