### ISSUE TITLE
Support for newer versions of dex

### ISSUE THREAD

**Issue by AriaMoradi** [ThexXTURBOXx/dex2jar#3]
Any plans for supporting newer versions of dex?

Looks like dex version 039 and 040 exist now.

**Comment by ThexXTURBOXx** [comment]
I will try to take a look into that. Do you have some example APK that fails when doing `dex2jar` or are you trying to do `jar2dex`?

**Comment by AriaMoradi** [comment]
> I will try to take a look into that. Do you have some example APK that fails when doing `dex2jar` or are you trying to do `jar2dex`?

This issue is mostly about forwarding thinking.

I haven't tried using your fork, but Lanchon's successfully converts apks from https://github.com/tachiyomiorg/tachiyomi-extensions, their SDK config is here: https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/buildSrc/src/main/kotlin/AndroidConfig.kt

Mostly speaking I think if you release a stable version and somehow forward potential Dex2Jar users here then we could know.

**Comment by ThexXTURBOXx** [comment]
If Lanchon's fork successfully converts them, mine should also work fine (as far as I can tell without trying it). If they don't, I added some regressions by accident.
That being said, I will try that tomorrow.

> The issue is mostly about forwarding thinking

Yes, that's a good point. I will read through the changelogs and so on and see what I need to add in order to support it :)

**Comment by nick-botticelli** [comment]
I found these resources that may help in adding support for the 2 new opcodes const-method-handle and const-method-type:

- https://android.googlesource.com/platform/art/+/master/test/979-const-method-handle/ - A test utilizing a class transformer to use the new opcodes
- https://android.googlesource.com/platform/art/+/master/test/dexdump/ - New opcode stuff in the form of a dex dump and a dump of the hex characters & opcodes titled const-method-handle.dex, .txt.
- https://source.android.com/devices/tech/dalvik/dalvik-bytecode#design - The two new opcodes are described in this specification.

It looks like DEX version 040 supports space characters in SimpleName as part of String syntax (https://source.android.com/devices/tech/dalvik/dex-format).

I am not experienced in adding new opcodes to dex2jar, but here is a quick draft of the two opcodes I placed in Op class
```
CONST_METHOD_HANDLE(0xfe, "const-method-handle", kFmt21c, kIndexMethodHandle, K_INSTR_CAN_CONTINUE, true),
CONST_METHOD_TYPE(0xff, "const-method-type", kFmt21c, kIndexMethodProtoRef, K_INSTR_CAN_CONTINUE, true),
```

**Comment by TimScriptov** [comment]
@AriaMoradi Support now dex 039-040?

**Comment by ThexXTURBOXx** [comment]
@TimScriptov Sadly no. However, I am open to any PRs :)

**Comment by ThexXTURBOXx** [comment]
Btw: If someone has an example of a dex version 39 file that fails in dex2jar, please share it with me. This will help me add support for the new opcodes.
I looked far and wide, but have not found an example of such a dex file yet.

**Comment by metzger100** [comment]
@ThexXTURBOXx 
Looks like they have a Dex Version 039 Problem with Smali Patcher over at [XDA](https://forum.xda-developers.com/t/module-smali-patcher-7-4.3680053/post-86039423).

**Comment by ThexXTURBOXx** [comment]
@metzger100 Yes, most applications have problems with it as far as I can tell. When I have some free time, I might investigate the issue a bit further :)

**Comment by ThexXTURBOXx** [comment]
I tagged this PR as being part of `Hacktoberfest`.
So, if someone is able to fix and properly test this issue, he is one step closer to completing `Hacktoberfest 2022` :)

**Comment by ThexXTURBOXx** [comment]
Resolved upstream
