### ISSUE TITLE
Merging other peoples' work

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/dex2jar#4]
@Aliucord @js6pak @Juby210 Would you allow me to merge some of your changes to this repo, such that some of your fixes are also included in BytecodeViewer or my builds on general?
That would be very nice from you :)

I know that the Apache license doesn't forbid me to just do it, but I still want to ask people before I do such stuff (I've had a very bad interaction with another developer once for basically the same reason).

**Comment by Juby210** [comment]
Hey, yeah feel free to do that. Thank you for your fork as well!

**Comment by js6pak** [comment]
Only https://github.com/Aliucord/dex2jar/commit/ccca98869aaf0f7998cc9a8ce462ecebe75c2375 seems anyhow useful but sure

**Comment by ThexXTURBOXx** [comment]
> Hey, yeah feel free to do that. 

Thank you very much for your approval :)
I will merge some of your changes in the next few minutes.

> Thank you for your fork as well!

You're more than welcome :)

> Only Aliucord@ccca988 seems anyhow useful but sure

I've noticed some few other fixes that might be useful as well. I will take a look at all of them :D
