### ISSUE TITLE
dex decompilation problem

### ISSUE THREAD

**Issue by BaLaLaLs** [ThexXTURBOXx/dex2jar#42]
I use the `sh d2j dex2jar. sh../classes. dex` command, The generated jar file is only 12KB. The dex file has 29M. 
[classes.dex](https://we.tl/t-AAqvYX1d0J)

**Comment by ThexXTURBOXx** [comment]
Alas, I am on vacation currently. I will check as soon as I am home again

**Comment by BaLaLaLs** [comment]
Wishing you a pleasant vacation

**Comment by ThexXTURBOXx** [comment]
I am back from my vacation, however, sadly I cannot download the dex file since the WeTransfer expired. Could you kindly send it again? Thanks!
