### ISSUE TITLE
When the dex version is 037 and above, the class version after dex2jar is 52. However, when using dx for jar2dex operations, a stack: overflow exception will occur

### ISSUE THREAD

**Issue by githubXiaowangzi** [ThexXTURBOXx/dex2jar#47]
dex2jar version：2.4
error：Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow
Uncaught translation error: com.android.dx.cf.code.SimException: stack: overflow
2 errors; aborting
example dex: [classes.dex](http://normalplayer.top:8880/member/view/fileDownload/classes.dex)

**Comment by githubXiaowangzi** [comment]
download url: http://normalplayer.top:8880/member/view/fileDownload/classes.dex

**Comment by ThexXTURBOXx** [comment]
Sorry, didn't mean to close this issue.
A class version of 52 is expected in these cases. I will take a look at jar2dex what is happening with the StackOverflowException

**Comment by githubXiaowangzi** [comment]
It should be noted that after forcibly changing the version number of this classs.dex from 039 to 035, and then performing the dex2jar and jar2dex operations, everything is normal.
In addition, using the dex2jar version v2.2-SNAPSHOT-2021-10-31, which is the version from asm5.0.3, the class file version obtained by converting the dex037 file is also 52, but at this time, jar2dex can be used normally.

**Comment by ThexXTURBOXx** [comment]
Can you try whether this one works? https://github.com/ThexXTURBOXx/dex2jar/actions/runs/7233350668/artifacts/1119250419
Please make sure to call `d2j-dex2jar` with the `-cf` parameter

**Comment by githubXiaowangzi** [comment]
Tested multiple dex files that originally had jar2dex exceptions, and the version linked above is functioning properly.

**Comment by ThexXTURBOXx** [comment]
Perfect, thanks for your feedback! The underlying issue is a change in ASM 6.0 which made `COMPUTE_MAXS` functioning incorrectly in many cases when Java 8 is selected as target.
My solution was to use `COMPUTE_FRAMES` instead and implementing my own (incomplete) logic which resolves superclasses.
Not the best solution, but probably the only one that works...

**Comment by githubXiaowangzi** [comment]
Thank you also for your outstanding contribution to the continuous updates of the dex2jar project!
