### ISSUE TITLE
dex2jar No errors were reported but i use jar in android studio ，The inheritance of the class cannot be obtained

### ISSUE THREAD

**Issue by sanlic** [ThexXTURBOXx/dex2jar#48]
![image](https://github.com/ThexXTURBOXx/dex2jar/assets/24861185/6d1b5e2f-5886-47e7-8631-2e4b2e6b049d)

**Comment by sanlic** [comment]
apk is potato chat

**Comment by ThexXTURBOXx** [comment]
Not reproducible on my end. The class exists and is accessible, as seen in the screenshot below.
The issue probably stems from the decompiler you are using and not from dex2jar directly (maybe there is an option to rename references to nested classes properly (the `$` should just be a `.`)).
![grafik](https://github.com/ThexXTURBOXx/dex2jar/assets/12763829/0d871104-1a26-47ca-8417-fa5001c06f8e)
