### ISSUE TITLE
Cannot convert Lcom/vungle/ads/internal/omsdk/Res;

### ISSUE THREAD

**Issue by GE-XX** [ThexXTURBOXx/dex2jar#54]
[summary.txt](https://github.com/user-attachments/files/17404955/summary.txt)

**Comment by Rabbit0w0** [comment]
Provide apk file if possible. I will try to investigate into this issue.

**Comment by ThexXTURBOXx** [comment]
@Rabbit0w0 See #25 - contributions for that are more than welcome :)
