### ISSUE TITLE
Can't open Jar

### ISSUE THREAD

**Issue by benni347** [ThexXTURBOXx/dex2jar#8]
Hello,
When I decompile it with the dex2jar.sh and try to open it in my java editor (Intellij IDEA) it doesn't open any ideas on how I can fix that?
Kind regards

**Comment by ThexXTURBOXx** [comment]
Hello, you can't open a `jar` file directly via IntelliJ.
You might try a decompiler first or add the jar as a library to the classpath inside IntelliJ.
Then, IntelliJ's decompiler (FernFlower) will do its work automatically.
If you need any decompiler, I would recommend https://github.com/Konloch/bytecode-viewer which features various decompilers in a single GUI.
A decompiler is used to reconstruct Java source files from jar or class files (the jar or class files are compiled Java code, which only the JVM can read and understand :)

**Comment by ThexXTURBOXx** [comment]
Closing this as off-topic
