### ISSUE TITLE
Reported file

### ISSUE THREAD

**Issue by Diasky** [ThexXTURBOXx/dex2jar#9]
[beatstar-error.zip](https://github.com/ThexXTURBOXx/dex2jar/files/7271319/beatstar-error.zip)

**Comment by Diasky** [comment]
What does "Fix NPE" mean?

**Comment by ThexXTURBOXx** [comment]
Sorry for not responding directly! `NPE` means `NullPointerException`. So, the new release should have fixed your issue.
If not, please report back again! :)

**Comment by Diasky** [comment]
Oh, dw thanks for helping me. Ill wait for the next release 👍

**Comment by ThexXTURBOXx** [comment]
No problem! :)
The new update is already available in the releases tab :)

**Comment by Diasky** [comment]
Oh i see it, and does it fixed this npe issue?

**Comment by ThexXTURBOXx** [comment]
It should fix it, yes :)
